{{- if eq .Values.deploymentMode "microservices" }}
{{- if .Values.query_scheduler.podDisruptionBudget -}}
{{- include "mimir.lib.podDisruptionBudget" (dict "ctx" $ "component" "query-scheduler") }}
{{- end -}}
{{- end }}